[package]
name = "day-08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gcd = "2.3.0"
indexmap = "2.1.0"


[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "day8"
harness = false
